ALTER TABLE users
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE books
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE loans
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;